### ISSUE TITLE
Allow optional undefined JSON properties

### ISSUE THREAD

**Issue by justmobiledev** [appvision-gmbh/json2typescript#161]
Hi,
first, thanks for creating this awesome library - which I like a lot.

Would it be possible to add a feature to allow optional undefined JSON properties?
For example, if I have a JSON like this:
person:
{
  name: "my name",
  title: "my title"
}
And for title create an optional property like this:
  @JsonProperty('title', String, true)
  title?: string;
  
  But let's say the backend deploys model changes frequently and I don't want to have to specify title as property and just ignore extra undefined properties, I don't think I can do this with your library.
  This feature would be very helpful. 
  Thanks!

**Comment by andreas-aeschlimann** [comment]
Hello, I am not quite sure if I understand your request.

You can already do this:
```
@JsonProperty('title', String, true)
title: string | undefined = undefined; // initialization is mandatory to make it work
```
If you do this, `title` will only be set if it is present in the JSON. Otherwise, the value will remain `undefined`. No exception will be thrown, unless `title` is given and not a string and not null. At the moment, null is the same as absent in the JSON.

**Comment by andreas-aeschlimann** [comment]
Closing this for now. Please report back if there is an issue!
